### ISSUE TITLE
Can't tab through brackets [] or angle brackets <>

### ISSUE THREAD

**Issue by Jont828** [JACooper/tab-through#1]
I went into the "Characters to consider tabbing through" part, and even after I added brackets, I still can't tab through them.

**Comment by Jont828** [comment]
I noticed that, when I typed in the bracket as `\]` instead of `]`, it worked. I'm assuming that this plugin uses regex to search, so I'm guessing that escaping the bracket would fix it. In that case, it seems like regex code is being injected by the user inputted string, so maybe you would just need to see if the char is in the string instead of using a regex search.

**Comment by JACooper** [comment]
Huh. Thanks for reporting, I'll take a look when I can.
